### ISSUE TITLE
Principal

### ISSUE THREAD

**Issue by aleksbor** [SNikalaichyk/cUserRightsAssignment#2]
Hello, how do you format multiple strings for Principal entry? I'm getting cannot convert String[] to String errors when generating MOF with this entry:
Principal = 'Everyone','BUILTIN\Users','BUILTIN\Backup Operators'

**Comment by SNikalaichyk** [comment]
Hi @aleksbor!
`Principal` is a `[String]` by design.
You can use the following snippet to accomplish your task:
```powershell
'DOMAIN\User01', 'DOMAIN\User02', 'DOMAIN\User03' |
Select-Object -Unique -PipelineVariable principal |
ForEach-Object -Begin {$counter = 0} -Process {

    cUserRight ('BatchLogonRight{0}' -f (++$counter))
    {
        Ensure    = 'Present'
        Constant  = 'SeBatchLogonRight'
        Principal = $principal
    }

}
```

**Comment by aleksbor** [comment]
Yes, or list each entry separately for readability. 
Requesting to add support for multiple strings :)
